### ISSUE TITLE
Can I skip the vcpkg and build the OpenCV Contrib for UWP directly?

### ISSUE THREAD

**Issue by CommanderLee** [Microsoft/MixedRealityToolkit#176]
Hello, I am trying to build the Spector View (iOS) for HoloLens. I am stuck on the first step: I cannot install the vcpkg on my machine. I opened an issue on the [vcpkg repo](https://github.com/Microsoft/vcpkg/issues/4079). I have checked and confirmed that: I am using Windows 10 (17134), I have Windows SDK installed (17134 and 16299), and I have a working VS 2017 Community (15.7.6). 

Since I haven't figure out the problem, I am wondering if I can skip this step. I tried to follow [this article](https://medium.com/@rabbi.cse.sust.bd/how-to-build-opencv-for-universal-windows-platform-uwp-1a642ec09955), but got tons of errors while trying to build the solution from VS. I got nothing in the bin/lib folders. 

Thank you for your time. It will be great if you can give me suggestions on the vcpkg problems and/or the OpenCV + UWP problems.

**Comment by timGerken** [comment]
@TobyGilbert-ms

**Comment by TobyGilbert-ms** [comment]
@CommanderLee  Installing vcpkg is just meant to be for convience when building the OpenCV libs for UWP.   If this is causing you issues you can just build the libraries for UWP and copy them into the relevant folders in the Unity project.   

Looking at that article it seems like following those steps should successfully build the UWP libs.  The only changes you will have to make is when configuring cmake, search for OPENCV_EXTRA_MODULES_PATH and point this at the opencv contrib modules directory.  Its also worth noting that we don't need all the opencv modules for spectator view so when configuring cmake you only need to check the following `BUILD_opencv_[moduleName]` options. 

- BUILD_opencv_aruco
- BUILD_opencv_calib3d
- BUILD_opencv_ccalib
- BUILD_opencv_core
- BUILD_opencv_features2d
- BUILD_opencv_flann
- BUILD_opencv_imgproc

You can uncheck all other `BUILD_opencv_[moduleName]` options.  This may at least reduces the number of errors your getting to the ones we care about.

**Comment by CommanderLee** [comment]
@TobyGilbert-ms  Thank you so much for your help. Based on your suggestion I managed to build the OpenCV for UWP (update: opencv_imgcodecs and opence_highgui is also required based on my debugging process). Now I am building the Apps for SpectorView using the example scenes from the MRTK.

While building for iOS, I got some problems (attached below). I noticed that the instruction said "_ensure to remove the GLTF component of MRTK as this is not yet compatibile with this platform_".  I am not sure what I am supposed to do, and I just deleted the 'HoloToolkit\Utilities\Scripts\GLTF' folder. Is there anything I should take care of other than clicking the "IPhone" button from the SpectorView prefab?

Thank you so much for your help.

Details of the problem:
[1]
Failed running C:\Program Files\Unity2018.2\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --map-file-parser="C:\Program Files\Unity2018.2\Editor\Data\Tools\MapFileParser\MapFileParser.exe" --assembly="C:\Users\zhen\Documents\GitHub\MixedRealityToolkit-Unity\Temp\StagingArea\Data\Managed\Assembly-CSharp.dll" --assembly="C:\Users\zhen\Documents\GitHub\MixedRealityToolkit-Unity\Temp\StagingArea\Data\Managed\UnityEngine.UI.dll" --assembly="C:\Users\zhen\Documents\GitHub\MixedRealityToolkit-Unity\Temp\StagingArea\Data\Managed\UnityEngine.Networking.dll" --assembly="C:\Users\zhen\Documents\GitHub\MixedRealityToolkit-Unity\Temp\StagingArea\Data\Managed\UnityEngine.dll" --generatedcppdir="C:\Users\zhen\Documents\GitHub\MixedRealityToolkit-Unity\Temp\il2cppOutput\il2cppOutput" 

stdout:
IL2CPP error for method 'System.Void Newtonsoft.Json.Linq.JObject::InternalPropertyChanged(Newtonsoft.Json.Linq.JProperty)' in assembly 'C:\Users\zhen\Documents\GitHub\MixedRealityToolkit-Unity\Temp\StagingArea\Data\Managed\Newtonsoft.Json.dll'
Additional information: Build a development build for more information. Exception of type 'System.Exception' was thrown.
il2cpp.exe didn't catch exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at Unity.IL2CPP.Metadata.VTableBuilder.SetupMethodSlotsForInterface(TypeReference typeReference)
   at Unity.IL2CPP.Metadata.VTableBuilder.SetupInterfaceOffsets(TypeReference type, Int32& currentSlot)
   at Unity.IL2CPP.Metadata.VTableBuilder.VTableFor(TypeReference typeReference, TypeResolver resolver)
   at Unity.IL2CPP.Metadata.VTableBuilder.IndexFor(MethodDefinition method)
   at Unity.IL2CPP.MethodBodyWriter.VirtualCallFor(IGeneratedMethodCodeWriter writer, MethodReference method, MethodReference unresolvedMethod, IEnumerable`1 args, TypeResolver typeResolver, IRuntimeMetadataAccess runtimeMetadataAccess, VTableBuilder vTableBuilder)
   at Unity.IL2CPP.MethodBodyWriter.GetMethodCallExpression(IGeneratedMethodCodeWriter writer, MethodReference callingMethod, MethodReference methodToCall, MethodReference unresolvedMethodtoCall, TypeResolver typeResolverForMethodToCall, MethodCallType callType, IRuntimeMetadataAccess runtimeMetadataAccess, VTableBuilder vTableBuilder, IEnumerable`1 argumentArray, Boolean useArrayBoundsCheck, Func`2 addUniqueSuffix)
   at Unity.IL2CPP.MethodBodyWriter.CallExpressionFor(MethodReference callingMethod, MethodReference unresolvedMethodToCall, MethodCallType callType, List`1 poppedValues, Func`2 addUniqueSuffix, Boolean emitNullCheckForInvocation)
   at Unity.IL2CPP.MethodBodyWriter.ProcessInstruction(Node node, InstructionBlock block, Instruction& ins)
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node node)
   at Unity.IL2CPP.MethodBodyWriter.Generate()
   at Unity.IL2CPP.MethodWriter.<>c__DisplayClass0_0.<WriteMethodDefinition>b__0(IGeneratedMethodCodeWriter bodyWriter, IRuntimeMetadataAccess metadataAccess)
   at Unity.IL2CPP.CodeWriterExtensions.WriteMethodWithMetadataInitialization(IGeneratedMethodCodeWriter writer, String methodSignature, String methodFullName, Action`2 writeMethodBody, String uniqueIdentifier, MethodReference methodRef)
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(IGeneratedMethodCodeWriter writer, MethodReference method, IMethodCollector methodCollector, IMethodVerifier methodVerifier, ISourceAnnotationWriter sourceAnnotationWriter, IIcallMappingService icallMapping, VTableBuilder vtableBuilder)
   at Unity.IL2CPP.SourceWriter.<>c__DisplayClass12_0.<WriteMethodSourceFiles>b__0(IGeneratedMethodCodeWriter writer, TypeReference type)
   at Unity.IL2CPP.SourceWriter.WriteEqualSizedChunks[T](NPath outputDir, IEnumerable`1 items, String fileName, Int64 chunkSize, Action`2 writeItemAction, SourceWritingContext sourceWritingContext)
   at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles(NPath outputDirectory, SourceWritingContext sourceWritingContext, String fileName, IEnumerable`1 typeList, IMethodCollector methodCollector, Boolean writeMarshalingDefinitions)
   at Unity.IL2CPP.SourceWriter.Write(NPath outputDir, SourceWritingContext sourceWritingContext, ReadOnlyCollection`1 assemblyDefinitions, IMethodCollector methodCollector, IInteropDataCollector interopDataCollector)
   at Unity.IL2CPP.AssemblyConverter.Apply()
   at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder, NPath executableAssembiesFolder, NPath monoLibFolder, NPath monoEtcFolder, NPath[] searchDirectories, String entryAssemblyName, NPath[] extraTypesFiles)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at Unity.IL2CPP.Metadata.VTableBuilder.SetupMethodSlotsForInterface(TypeReference typeReference)
   at Unity.IL2CPP.Metadata.VTableBuilder.SetupInterfaceOffsets(TypeReference type, Int32& currentSlot)
   at Unity.IL2CPP.Metadata.VTableBuilder.VTableFor(TypeReference typeReference, TypeResolver resolver)
   at Unity.IL2CPP.Metadata.VTableBuilder.IndexFor(MethodDefinition method)
   at Unity.IL2CPP.MethodBodyWriter.VirtualCallFor(IGeneratedMethodCodeWriter writer, MethodReference method, MethodReference unresolvedMethod, IEnumerable`1 args, TypeResolver typeResolver, IRuntimeMetadataAccess runtimeMetadataAccess, VTableBuilder vTableBuilder)
   at Unity.IL2CPP.MethodBodyWriter.GetMethodCallExpression(IGeneratedMethodCodeWriter writer, MethodReference callingMethod, MethodReference methodToCall, MethodReference unresolvedMethodtoCall, TypeResolver typeResolverForMethodToCall, MethodCallType callType, IRuntimeMetadataAccess runtimeMetadataAccess, VTableBuilder vTableBuilder, IEnumerable`1 argumentArray, Boolean useArrayBoundsCheck, Func`2 addUniqueSuffix)
   at Unity.IL2CPP.MethodBodyWriter.CallExpressionFor(MethodReference callingMethod, MethodReference unresolvedMethodToCall, MethodCallType callType, List`1 poppedValues, Func`2 addUniqueSuffix, Boolean emitNullCheckForInvocation)
   at Unity.IL2CPP.MethodBodyWriter.ProcessInstruction(Node node, InstructionBlock block, Instruction& ins)
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node node)
   at Unity.IL2CPP.MethodBodyWriter.Generate()
   at Unity.IL2CPP.MethodWriter.<>c__DisplayClass0_0.<WriteMethodDefinition>b__0(IGeneratedMethodCodeWriter bodyWriter, IRuntimeMetadataAccess metadataAccess)
   at Unity.IL2CPP.CodeWriterExtensions.WriteMethodWithMetadataInitialization(IGeneratedMethodCodeWriter writer, String methodSignature, String methodFullName, Action`2 writeMethodBody, String uniqueIdentifier, MethodReference methodRef)
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(IGeneratedMethodCodeWriter writer, MethodReference method, IMethodCollector methodCollector, IMethodVerifier methodVerifier, ISourceAnnotationWriter sourceAnnotationWriter, IIcallMappingService icallMapping, VTableBuilder vtableBuilder)
   at Unity.IL2CPP.SourceWriter.<>c__DisplayClass12_0.<WriteMethodSourceFiles>b__0(IGeneratedMethodCodeWriter writer, TypeReference type)
   at Unity.IL2CPP.SourceWriter.WriteEqualSizedChunks[T](NPath outputDir, IEnumerable`1 items, String fileName, Int64 chunkSize, Action`2 writeItemAction, SourceWritingContext sourceWritingContext)
   at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles(NPath outputDirectory, SourceWritingContext sourceWritingContext, String fileName, IEnumerable`1 typeList, IMethodCollector methodCollector, Boolean writeMarshalingDefinitions)
   at Unity.IL2CPP.SourceWriter.Write(NPath outputDir, SourceWritingContext sourceWritingContext, ReadOnlyCollection`1 assemblyDefinitions, IMethodCollector methodCollector, IInteropDataCollector interopDataCollector)
   at Unity.IL2CPP.AssemblyConverter.Apply()
   at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder, NPath executableAssembiesFolder, NPath monoLibFolder, NPath monoEtcFolder, NPath[] searchDirectories, String entryAssemblyName, NPath[] extraTypesFiles)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunProgram(Program, String, String, String, CompilerOutputParserBase) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:128)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase, Action`1) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:73)
UnityEditorInternal.IL2CPPBuilder:RunIl2CppWithArguments(List`1, Action`1, String) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:380)
UnityEditorInternal.IL2CPPBuilder:ConvertPlayerDlltoCpp(ICollection`1, String, String, Boolean) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:361)
UnityEditorInternal.IL2CPPBuilder:Run() (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:178)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:35)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

[2]
Exception: C:\Program Files\Unity2018.2\Editor\Data\il2cpp/build/il2cpp.exe did not run properly!
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:130)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1 setupStartInfo) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:73)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1 arguments, System.Action`1 setupStartInfo, System.String workingDirectory) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:380)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (ICollection`1 userAssemblies, System.String outputDirectory, System.String workingDirectory, Boolean platformSupportsManagedDebugging) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:361)
UnityEditorInternal.IL2CPPBuilder.Run () (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:178)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, System.Action`1 modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:35)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (BuildSettings bs, UnityEditor.iOS.ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:825)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (BuildSettings bs, UnityEditor.iOS.ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:660)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (PostProcessorSettings postProcessorSettings, BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:611)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:37)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at C:/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:27)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTargetGroup targetGroup, BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:287)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by santanor** [comment]
Hello @CommanderLee

Make sure that the `Api Compatibility Level*` is set to `.NET 2.0` and **not** to `.NET 2.0 Subset` I think the error you got is very similar to something I encountered last week and doing that fixed it. 

You can change the `Api Compatibility Level*` from `Player Settings` under `Other Settings` 

Let us know if that fixes it

**Comment by JoseSantano-ms** [comment]
Hello @CommanderLee

Make sure that the Api Compatibility Level* is set to .NET 2.0 and not to .NET 2.0 Subset I think the error you got is very similar to something I encountered last week and doing that fixed it.

You can change the Api Compatibility Level* from Player Settings under Other Settings

Let us know if that fixes it

**Comment by CommanderLee** [comment]
@JoseSantano-ms That's the problem. The errors are gone after I set it to '.NET 2.0' instead of '.NET 2.0 Subset'. Thank you so much! Now I am able to build the iOS project smoothly. 

One more question about running the HoloLens version: the instruction said "Copy the following dlls (e.g., opencv_aruco342dll) to the directory HoloToolkit\SpectatorView\Plugins\WSA\x86\". But actually the destination path doesn't exist, and I am not sure where I should place these dlls. 

I will let you know whether I could deploy these projects to my iPad and HoloLens and test the Spector View.

**Comment by JoseSantano-ms** [comment]
Hi @CommanderLee I'm glad you could fix the problem. For the dlls, just create the directory and put them there :)

**Comment by CommanderLee** [comment]
Hi @JoseSantano-ms Thank you for your suggestion. Now I can deploy the projects for iOS and HoloLens, but got another problem: My iPad can display the OpenCV marker, and when I turn the HoloLens camera towards it, several exceptions pop up and I cannot proceed. 

Details are attached. Please let me know if there are other stuff I need to check. Basically I am following the instructions, using the Unity example scene under "HoloToolkit-Examples\SpectatorView\Scenes". I noticed that the scene components and prefabs are not identical to the screenshots in the document anymore, but those important pieces (e.g., SpectatorView and NetworkManager) are okay and I didn't change them.

Since these exceptions happened when I start the iOS App, I guess that this HoloLens App detected the new joining iOS client, but failed to start the camera/recognition, but I don't know why. I checked the permissions in HoloLens-settings and it has the WebCam permission.

Thank you so much for your time.

Attached (exception info from VS):

Setting up 1 worker threads for Enlighten.

  Thread -> id: f40 -> priority: 1 

DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
 
(Filename: C:\buildslave\unity\build\Runtime/SceneManager/SceneManager.cpp Line: 495)


Exception thrown: 'System.NotImplementedException' in WinRTBridge.dll
'MixedRealityToolkit-Unity.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\MixedRealityToolkit-UnityVS.Release_x86.zhen\System.Diagnostics.StackTrace.dll'. Cannot find or open the PDB file.
Exception: The method or operation is not implemented.
Type: System.NotImplementedException
Module: WinRTBridge
InnerException: <No Data>
AdditionalInfo:MarshalFirstFieldIntoNativePtr type: UnityEngine.XR.WSA.WebCam.PhotoCaptureFrame
   at WinRTBridge.Marshalling.MarshalFirstFieldIntoNativePtr(Object instance)
 
(Filename:  Line: 0)


Exception thrown: 'System.ArgumentNullException' in UnityEngineProxy.dll
ArgumentNullException: Value cannot be null.
Parameter name: _unity_self
   at UnityEngineProxy.InternalCalls.PhotoCaptureFrame_CUSTOM_GetDataLength(Object self)
   at UnityEngine.XR.WSA.WebCam.PhotoCaptureFrame..ctor(IntPtr nativePtr)
   at UnityEngine.XR.WSA.WebCam.PhotoCapture.InvokeOnCapturedPhotoToMemoryDelegate(OnCapturedToMemoryCallback callback, Int64 hResult, IntPtr photoCaptureFramePtr)
   at UnityEngine.XR.WSA.WebCam.PhotoCapture.$Invoke10(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)


Exception thrown: 'System.ArgumentOutOfRangeException' in System.Private.CoreLib.ni.dll
An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in System.Private.CoreLib.ni.dll
Positive number required.

The program '[3676] MixedRealityToolkit-Unity.exe' has exited with code -1 (0xffffffff).

**Comment by ChauNTran** [comment]
@CommanderLee  Did you also need zlib1.dll and SpectatorViewPlugin.dll beside the opencv dll files?

**Comment by ras0219-msft** [comment]
We're fixing this issue upstream in vcpkg; the branch `dev/roschuma/4574` has a fix and will be checked in to master once we have confirmed it doesn't regress other platforms.

Sorry for the trouble!

**Comment by ras0219-msft** [comment]
The fix is now checked in to vcpkg master.

**Comment by CommanderLee** [comment]
@ras0219-msft  Now the vcpkg setup works fine. Thank you for your help.
